### ISSUE TITLE
Netlify CMS: Inject configuration during build

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-core#2268]
#### User Story

To ease the configuration burden on users AND have better control over the authentication backend, determine whether injecting the required configuration for authenticating with Github via Federalist during build makes sense, and implement.

I imagine staging/production builds would inject corresponding urls for authentication. The configuration lives in the Netlify Configuration file, typically in `admin/config.yml` though this is configurable.

```
backend:
  name: github
  repo: <repo> (Ex. 18F/federalist-uswds-jekyll)
  base_url: <federalist url> (Ex. http://federalistapp-staging.18f.gov)
  auth_endpoint: external/auth/github
```

#### Acceptance Criteria
- [x] Check to see if `admin` folder exists in base template directory, if *true*, overwrite `config.yml` with default settings.

For callback URL use: GITHUB_CLIENT_EXTERNAL_CALLBACK_URL which should have the value of <host>/external/auth/github/callback
